### PR TITLE
Add the /index.html and /rss.xml routes.

### PR DESCRIPTION
**Pull request by russel**
I hope this is the right way of adding /index.html as an alias for / and adding /rss.xml so the feed readers can get it.

### CODE REVIEW

**Comment by russel** [comment]
Wrong rss.xml path? Should /rss.xml or /site/rss.xml be the correct path?

The whole thing works on testconference.accu.org but not conference.accu.org with the present set up.

Accept the pull request for now for consistency.

**Comment by benignbala** [comment]
Thanks :) And yes,  /index.html is how we add it as an alias. It should be /rss.xml. All URLs in nikola will automatically take the /site prefix because that's how the Blueprint is registered

**Comment by russel** [comment]
I have deployed the flask material and the Nikola material and it sort of works on testconference but not on conference. I am getting confused since the two filestores are the same.

**Comment by benignbala** [comment]
So, /site/index.html and /site/rss.xml fail to resolve, but just http://conference.accu.org/ works. I'll try to figure out what is causing this discrepency.

Meanwhile, lesscpy doesn't seem to understand rgba(...) and image-height(....) LESS APIs. That's why we are seeing the background in white. But given that ACCU logo is in blue, I guess white background would be more ideal since blue on black will not look good.

**Comment by russel** [comment]
I am going to have to leave this for today. but yes https://conference.accu.org/index.html and https://conference.accu.org/site/index.html do not resolve. This matters much more for rss.xml. I think currently both repositories are fully up to date and deployed.

**Comment by benignbala** [comment]
@russel, Sure, I'll try to see what's happening. Thanks

**Pull request merged**
