### PR TITLE
Simplify the location of the Nikola generated source

### PR DESCRIPTION
**Pull request by russel**
By making the assumption that the static directory is a sibling of the view.py controller that handles the /site/ URL, the MODULE_PATH configuration variable can be removed. However I am not sure this is the right thing to do. Maybe it is better to have the Nikola generated material not in the directory heirarchy of  the Flask application, in which case maybe MODULE_PATH might be better renamed NIKOLA_STATIC_PATH or some such.

This pull request is really to raise the debate.

### CODE REVIEW

**Comment by benignbala** [comment]
We can assume that static directory is a sibling of the view.py. But what I am trying is to use a "shared" static folder between the nikola blueprint and the proposals blueprint. Once I get that done, we can use either  NIKOLA_STATIC_PATH or simple STATIC_PATH. Thanks

**Comment by russel** [comment]
So does the eventual goal mean we should not bind the location of the Nikola generated material quite as this proposal enforces?

Having a variable in the configuration is fine as long as the value is not a literal, but is a value calculated at initialisation time. Given the initialisation is a Python module, this should be easy.

Mayhap we should reject this pull request and go with the configuration variable from now, with an updated code that doesn't use literal paths or Path.cwd().

**Comment by benignbala** [comment]
True, what we will need is the deployment path of the top level folder containing accuconf_config.py concatenated with "accuconf/static". I have now got both the blue prints to share the same static folder. So, the contents of nikola/output/* should be copied into <DEPLOYMENT_PATH>/accuconf/static/ and we will have both sites rendered fine.

**Comment by benignbala** [comment]
BTW, this was a good learning for me. Thanks for that :) I had use Path.cwd() in a few occasions at work too. Never realised it could be so fragile. I'll try to avoid relying on that as much as possible and stick to using evaluated/computed paths. Thanks

**Comment by russel** [comment]
OK, I will reject this pull request and come up with an alternative based on the discussions.

**Pull request closed without merging**
